#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    a=arr
    b=max(arr)
    c=min(arr)
    arr.sort()
    print(sum(a)-b,end=" ")
    print(sum(arr)-c,end=" ")

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
